const additionalData = [
    {
        "videoFile": "https://res.cloudinary.com/dybgs03yy/video/upload/v1726385255/abcd123.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/quantum_computing_thumbnail.png",
        "title": "Quantum Computing Explained: Unraveling the Future of Technology",
        "description": "Explore the revolutionary field of quantum computing with a detailed explanation of its principles, potential applications, and how it differs from classical computing. This video provides insights into how quantum computers could transform industries ranging from cryptography to materials science.",
        "duration": 310,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "science"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://res.cloudinary.com/dybgs03yy/video/upload/v1726385255/efgh567.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/climate_change_thumbnail.png",
        "title": "Climate Change and Tech: Challenges and Innovations",
        "description": "This video examines the effects of climate change on various ecosystems around the world, highlighting the impact on biodiversity, weather patterns, and human societies. It also discusses potential solutions and mitigation strategies to address these environmental challenges.",
        "duration": 340,
        "views": 0,
        "isPublished": true,
        "categories": ["environment", "education"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://res.cloudinary.com/dybgs03yy/video/upload/v1726385255/hijk789.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/renewable_energy_thumbnail.png",
        "title": "Innovations in Renewable Energy: The Future of Sustainable Tech",
        "description": "Dive into the latest advancements in renewable energy technologies, including breakthroughs in solar, wind, and geothermal energy. This video explores how these innovations are driving the transition to a more sustainable energy future.",
        "duration": 280,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "environment"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://res.cloudinary.com/dybgs03yy/video/upload/v1726385255/lmno012.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/genetics_thumbnail.png",
        "title": "Human Genetics and Tech: Revolutionizing Health and Medicine",
        "description": "Explore the fundamentals of human genetics, including how DNA influences health, disease, and inheritance. This video provides insights into genetic research, the implications of genetic disorders, and the potential of personalized medicine.",
        "duration": 320,
        "views": 0,
        "isPublished": true,
        "categories": ["science", "health"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://res.cloudinary.com/dybgs03yy/video/upload/v1726385255/opqr345.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/communication_technologies_thumbnail.png",
        "title": "The Evolution of Communication Tech: From Telegraph to Internet",
        "description": "Trace the development of communication technologies from the invention of the telegraph to the rise of the internet. This video highlights key milestones, technological innovations, and how they have shaped the way we connect and communicate.",
        "duration": 290,
        "views": 0,
        "isPublished": true,
        "categories": ["history", "technology"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/ai_in_healthcare.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/ai_in_healthcare.png",
        "title": "AI in Healthcare: Transforming Patient Care and Diagnosis",
        "description": "Learn how artificial intelligence is revolutionizing the healthcare industry, from improving diagnostics to providing personalized treatment plans.",
        "duration": 300,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "health"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/blockchain_explained.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/blockchain_explained.png",
        "title": "Blockchain Technology: Beyond Cryptocurrencies",
        "description": "Discover how blockchain is being used beyond cryptocurrencies, in fields like finance, supply chain, and data security.",
        "duration": 340,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "finance"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/5g_networks_future.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/5g_networks.png",
        "title": "The Future of 5G Networks: Connecting the World",
        "description": "Explore how 5G technology is set to revolutionize communication, powering everything from smart cities to autonomous vehicles.",
        "duration": 320,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "communications"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/vr_in_education.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/vr_in_education.png",
        "title": "Virtual Reality in Education: Transforming Learning Experiences",
        "description": "Learn how virtual reality is enhancing the educational landscape by providing immersive and interactive learning experiences.",
        "duration": 280,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "education"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/ai_and_automation.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/ai_and_automation.png",
        "title": "AI and Automation: Reshaping the Workforce",
        "description": "Explore how artificial intelligence and automation are transforming industries, enhancing efficiency, and creating new job opportunities.",
        "duration": 330,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "business"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/quantum_computing_applications.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/quantum_computing_applications.png",
        "title": "Real-World Applications of Quantum Computing",
        "description": "Explore the current and future applications of quantum computing in industries like cryptography, chemistry, and material science.",
        "duration": 310,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "science"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/future_of_biotech.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/future_of_biotech.png",
        "title": "The Future of Biotechnology: Innovations in Medicine",
        "description": "Discover how biotechnology is driving innovations in medicine, from gene editing to advanced drug development.",
        "duration": 295,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "health"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/space_mining_tech.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/space_mining_tech.png",
        "title": "Space Mining: Exploring New Frontiers in Technology",
        "description": "Explore the emerging technology of space mining and how it could revolutionize resource extraction on Earth and beyond.",
        "duration": 315,
        "views": 0,
        "isPublished": true,
        "categories": ["space", "technology"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/cybersecurity_in_the_iot_era.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/cybersecurity_iot.png",
        "title": "Cybersecurity in the IoT Era: Protecting Connected Devices",
        "description": "Learn how cybersecurity is evolving to meet the challenges of protecting millions of interconnected devices in the Internet of Things.",
        "duration": 300,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "security"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/digital_twins.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/digital_twins.png",
        "title": "Digital Twins: The Future of Real-World Simulations",
        "description": "Explore the world of digital twins and how these virtual replicas of real-world objects are transforming industries like manufacturing and healthcare.",
        "duration": 280,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "science"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/smart_cities_innovation.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/smart_cities.png",
        "title": "Smart Cities: Building the Future of Urban Living",
        "description": "Discover how smart cities are integrating technology to create more sustainable, efficient, and livable urban environments.",
        "duration": 320,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "urban development"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/future_of_smart_homes.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/smart_homes.png",
        "title": "The Future of Smart Homes: Tech-Enhanced Living",
        "description": "Learn how smart home technologies are enhancing everyday life with automation, voice control, and energy-saving solutions.",
        "duration": 290,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "home automation"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/tech_for_social_good.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/social_good_tech.png",
        "title": "Tech for Social Good: Innovations Changing the World",
        "description": "Explore how technology is being used to address global challenges, from providing clean water to delivering education in remote areas.",
        "duration": 330,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "social impact"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/self_driving_cars_explained.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/self_driving_cars.png",
        "title": "Self-Driving Cars: The Future of Autonomous Transportation",
        "description": "Learn about the advancements in autonomous vehicle technology and how self-driving cars could revolutionize the future of transportation.",
        "duration": 310,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "automotive"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/drone_tech_future.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/drone_tech.png",
        "title": "The Future of Drone Technology: From Delivery to Disaster Response",
        "description": "Explore how drone technology is advancing, from delivering packages to providing critical support in disaster response efforts.",
        "duration": 290,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "aviation"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/ai_ethics.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/ai_ethics.png",
        "title": "AI Ethics: Balancing Innovation and Responsibility",
        "description": "A deep dive into the ethical challenges and considerations that come with AI development and implementation.",
        "duration": 340,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "ethics"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/nanotech_innovation.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/nanotech_innovation.png",
        "title": "Nanotechnology: Shaping the Future of Science",
        "description": "Explore the cutting-edge innovations in nanotechnology and its applications in medicine, electronics, and materials.",
        "duration": 300,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "science"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/blockchain_finance.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/blockchain_finance.png",
        "title": "Blockchain in Finance: The Future of Transactions",
        "description": "Learn how blockchain technology is revolutionizing finance, from digital currencies to secure transactions.",
        "duration": 320,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "finance"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/robotics_future.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/robotics_future.png",
        "title": "The Future of Robotics: From Industry to Everyday Life",
        "description": "Discover how advancements in robotics are transforming industries and making their way into everyday life.",
        "duration": 310,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "robotics"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/space_travel_future.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/space_travel.png",
        "title": "Space Travel: The Next Frontier of Human Exploration",
        "description": "Explore the latest advancements in space travel, including Mars missions, lunar bases, and commercial space tourism.",
        "duration": 350,
        "views": 0,
        "isPublished": true,
        "categories": ["space", "technology"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/renewable_energy_innovations.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/renewable_energy.png",
        "title": "Innovations in Renewable Energy: Powering the Future",
        "description": "Learn how new technologies in renewable energy are transforming the way we generate and consume power.",
        "duration": 330,
        "views": 0,
        "isPublished": true,
        "categories": ["energy", "technology"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/3d_printing_revolution.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/3d_printing.png",
        "title": "3D Printing: Revolutionizing Manufacturing",
        "description": "Explore the world of 3D printing and how it’s revolutionizing manufacturing, prototyping, and product design.",
        "duration": 290,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "manufacturing"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/artificial_general_intelligence.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/ag_intelligence.png",
        "title": "Artificial General Intelligence: The Next Leap in AI",
        "description": "A deep dive into the concept of Artificial General Intelligence and how it differs from today's AI systems.",
        "duration": 340,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "AI"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/bioengineering_future.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/bioengineering_future.png",
        "title": "Bioengineering: Shaping the Future of Health",
        "description": "Discover how bioengineering is being used to develop new medical treatments, create artificial organs, and more.",
        "duration": 305,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "health"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/ai_in_art.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/ai_in_art.png",
        "title": "AI in Art: Creativity Meets Technology",
        "description": "Learn how artificial intelligence is being used to create innovative artworks, music, and other forms of digital creativity.",
        "duration": 270,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "art"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/sustainable_tech.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/sustainable_tech.png",
        "title": "Sustainable Technology: Innovating for a Greener Future",
        "description": "Explore how technological innovations are helping to create a more sustainable world, from green energy to eco-friendly materials.",
        "duration": 300,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "environment"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/human_brain_interface.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/brain_interface.png",
        "title": "Brain-Computer Interfaces: Bridging Minds and Machines",
        "description": "Explore the emerging world of brain-computer interfaces, which enable direct communication between the human brain and external devices.",
        "duration": 320,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "health"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/future_of_solar_power.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/solar_power.png",
        "title": "The Future of Solar Power: Energy from the Sun",
        "description": "Learn about the latest advancements in solar technology and how they’re making solar power more efficient and accessible.",
        "duration": 300,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "energy"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/fintech_innovation.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/fintech_innovation.png",
        "title": "FinTech Innovations: Changing the Face of Finance",
        "description": "Explore the cutting-edge innovations in FinTech that are revolutionizing banking, payments, and financial management.",
        "duration": 330,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "finance"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/ai_and_creativity.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/ai_and_creativity.png",
        "title": "AI and Creativity: Can Machines Be Truly Creative?",
        "description": "Discover how AI is being used in creative fields like music, writing, and visual arts, and explore the question: Can machines be truly creative?",
        "duration": 295,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "artificial intelligence"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/self_driving_cars.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/self_driving_cars.png",
        "title": "Self-Driving Cars: The Future of Transportation",
        "description": "Explore the advancements in autonomous vehicle technology and how it’s poised to change the way we travel.",
        "duration": 320,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "transportation"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/smart_city_tech.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/smart_city_tech.png",
        "title": "Smart Cities: Innovations in Urban Living",
        "description": "Discover how technology is transforming urban living with smart cities, from IoT devices to sustainable infrastructure.",
        "duration": 310,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "urban living"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/quantum_computing.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/quantum_computing.png",
        "title": "Quantum Computing: The Future of Processing Power",
        "description": "Learn how quantum computers are changing the landscape of technology and their potential applications in various industries.",
        "duration": 350,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "computing"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/future_of_work.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/future_of_work.png",
        "title": "The Future of Work: Automation and Human Collaboration",
        "description": "Explore the changing landscape of work as automation and AI play an increasing role in shaping industries and professions.",
        "duration": 290,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "work"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/healthcare_tech.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/healthcare_tech.png",
        "title": "Healthcare Technology: Innovations in Medicine",
        "description": "Learn how cutting-edge technology is revolutionizing healthcare, from telemedicine to AI-driven diagnostics.",
        "duration": 305,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "health"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/virtual_reality_future.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/virtual_reality.png",
        "title": "Virtual Reality: The Future of Immersive Experiences",
        "description": "Explore the latest developments in virtual reality technology and how it's changing industries from gaming to education.",
        "duration": 335,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "virtual reality"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/cybersecurity_trends.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/cybersecurity_trends.png",
        "title": "Cybersecurity Trends: Protecting Data in the Digital Age",
        "description": "Learn about the latest trends and strategies in cybersecurity to protect sensitive information from evolving digital threats.",
        "duration": 320,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "cybersecurity"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/ai_in_healthcare.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/ai_in_healthcare.png",
        "title": "AI in Healthcare: Revolutionizing Patient Care",
        "description": "Discover how AI is being used to enhance patient care, from diagnostics to personalized treatments in healthcare.",
        "duration": 300,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "health"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/drones_future.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/drones_future.png",
        "title": "Drones: The Future of Aviation and Beyond",
        "description": "Learn about the rapidly growing field of drone technology and its applications in industries ranging from delivery to security.",
        "duration": 330,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "aviation"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/augmented_reality_trends.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/augmented_reality.png",
        "title": "Augmented Reality: Trends in Mixed Reality Experiences",
        "description": "Explore the growing field of augmented reality and its impact on industries such as retail, education, and entertainment.",
        "duration": 340,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "augmented reality"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/smart_home_tech.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/smart_home_tech.png",
        "title": "Smart Home Technology: The Connected Future",
        "description": "Learn how smart home devices are transforming how we live, offering more convenience, security, and energy efficiency.",
        "duration": 315,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "home automation"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/blockchain_beyond_crypto.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/blockchain_beyond_crypto.png",
        "title": "Blockchain Beyond Cryptocurrency: Real-World Applications",
        "description": "Discover how blockchain technology is being used beyond cryptocurrencies in industries such as supply chain, healthcare, and more.",
        "duration": 325,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "blockchain"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/data_privacy_future.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/data_privacy.png",
        "title": "The Future of Data Privacy: Navigating the Digital World",
        "description": "Explore the challenges and future of data privacy in a world where personal data is increasingly collected and analyzed.",
        "duration": 310,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "data privacy"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/ai_in_finance.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/ai_in_finance.png",
        "title": "AI in Finance: Redefining Investment and Banking",
        "description": "Learn how AI is revolutionizing the finance industry, from robo-advisors to fraud detection and beyond.",
        "duration": 345,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "finance"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/edge_computing_revolution.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/edge_computing_revolution.png",
        "title": "Edge Computing: A Revolution in Data Processing",
        "description": "Discover how edge computing is transforming data processing by bringing computation closer to the source of data generation.",
        "duration": 300,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "computing"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/gene_editing_futute.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/gene_editing_future.png",
        "title": "Gene Editing: The Future of Genetic Medicine",
        "description": "Explore the cutting-edge developments in gene editing technologies like CRISPR and their potential to cure genetic diseases.",
        "duration": 320,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "health"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/future_of_renewables.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/future_of_renewables.png",
        "title": "Renewable Energy: Powering the Future",
        "description": "Learn how advancements in renewable energy technologies are shaping a more sustainable and energy-efficient world.",
        "duration": 340,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "energy"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/5g_impact_on_connectivity.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/5g_impact_on_connectivity.png",
        "title": "5G: The Impact on Connectivity and Innovation",
        "description": "Explore how 5G networks are revolutionizing mobile connectivity and enabling new technological innovations.",
        "duration": 315,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "connectivity"],
        "owner": "66e68c6798e5fdbd46e435e1"
      },
      {
        "videoFile": "https://tech-community.com/videos/climate_tech_solutions.mp4",
        "thumbnail": "https://tech-community.com/thumbnails/climate_tech_solutions.png",
        "title": "Climate Tech: Innovating to Combat Climate Change",
        "description": "Discover the technologies designed to combat climate change, from carbon capture to renewable energy solutions.",
        "duration": 325,
        "views": 0,
        "isPublished": true,
        "categories": ["technology", "climate"],
        "owner": "66e68c6798e5fdbd46e435e1"
      }
  ];
  
  
  module.exports = { data: additionalData };
  